// Code generated by hertz generator.

package api

import (
	"context"

	api "github.com/cloudwego/api_gateway/hertz_gateway/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// QueryStudent .
// @router student/query [GET]
func QueryStudent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.QueryStudentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.QueryStudentResponse)

	c.JSON(consts.StatusOK, resp)
}

// InsertStudent .
// @router student/insert [POST]
func InsertStudent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.InsertStudentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.InsertStudentResponse)

	c.JSON(consts.StatusOK, resp)
}
