// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api "github.com/cloudwego/api_gateway/hertz_gateway/biz/router/api"
	calculator "github.com/cloudwego/api_gateway/hertz_gateway/biz/router/calculator"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	
	api.Register(r)

	calculator.Register(r)
}
