// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/api_gateway/hertz_gateway/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts("127.0.0.1:8080"))

	h.Use(middleware.ProtocolTranslation())

	register(h)
	h.Spin()
}
