// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/api_gateway/hertz_gateway/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app/server"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
)

func main() {
	tracer, trcCfg := hertztracing.NewServerTracer()
	h := server.Default(
		server.WithHostPorts("127.0.0.1:8080"),
		tracer,
	)

	h.Use(middleware.ProtocolTranslation())

	register(h)
	h.Spin()
}
