// Code generated by hertz generator. DO NOT EDIT.

package main

import (
	// router "github.com/cloudwego/api_gateway/hertz_gateway/biz/router"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// register registers all routers.
func register(r *server.Hertz) {

	// not used
	// router.GeneratedRegister(r)

	customizedRegister(r)
}
