// Code generated by hertz generator.

package main

import (
	"context"
	"net/http"
	"os"
	"strings"

	"github.com/cloudwego/api_gateway/hertz_gateway/biz/handler"
	"github.com/cloudwego/api_gateway/hertz_gateway/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/genericclient"
	"github.com/cloudwego/kitex/pkg/generic"
	"github.com/cloudwego/kitex/pkg/loadbalance"
	"github.com/kitex-contrib/registry-nacos/resolver"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/", func(ctx context.Context, c *app.RequestContext) {
		c.JSON(http.StatusOK, "api-gateway is running")
	})

	registerGateway(r)

	// your code ...
}

func registerGateway(r *server.Hertz) {
	group := r.Group("/gateway").Use(middleware.ProtocolTranslation())

	if middleware.IdlMap == nil {
		middleware.IdlMap = make(map[string]generic.DescriptorProvider)
	}
	idlPath := "../idl/"
	c, err := os.ReadDir(idlPath)
	if err != nil {
		hlog.Fatalf("new thrift file provider failed: %v", err)
	}
	nacosResolver, err := resolver.NewDefaultNacosResolver()
	if err != nil {
		hlog.Fatalf("err:%v", err)
	}

	for _, entry := range c {
		/*
			if entry.IsDir() || entry.Name() == "common.thrift" {
				continue
			}
		*/
		if entry.Name() == "student_api.thrift" {
			svcName := strings.ReplaceAll(entry.Name(), ".thrift", "")

			provider, err := generic.NewThriftFileProvider(entry.Name(), idlPath)
			if err != nil {
				hlog.Fatalf("new thrift file provider failed: %v", err)
				break
			}

			g, err := generic.JSONThriftGeneric(provider)
			if err != nil {
				hlog.Fatal(err)
			}

			loadbalanceropt := client.WithLoadBalancer(loadbalance.NewWeightedRoundRobinBalancer())
			cli, err := genericclient.NewClient(
				svcName,
				g,
				client.WithResolver(nacosResolver),
				loadbalanceropt,
			)
			if err != nil {
				hlog.Fatal(err)
			}

			handler.SvcMap[svcName] = cli
			group.POST("/:svc", handler.Gateway)
		}
	}
}
