// Code generated by Kitex v0.6.0. DO NOT EDIT.

package userprofileservice

import (
	"context"
	userauth "github.com/cloudwego/api_gateway/kitex_server/kitex_gen/userAuth"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetProfile(ctx context.Context, username string, callOptions ...callopt.Option) (r *userauth.UserProfile, err error)
	UpdateProfile(ctx context.Context, username string, profile *userauth.UserProfile, callOptions ...callopt.Option) (r bool, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserProfileServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserProfileServiceClient struct {
	*kClient
}

func (p *kUserProfileServiceClient) GetProfile(ctx context.Context, username string, callOptions ...callopt.Option) (r *userauth.UserProfile, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProfile(ctx, username)
}

func (p *kUserProfileServiceClient) UpdateProfile(ctx context.Context, username string, profile *userauth.UserProfile, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProfile(ctx, username, profile)
}
