// Code generated by hertz generator.

package calculator

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _calculatorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _calculateMw() []app.HandlerFunc {
	// your code...
	return nil
}
